### ISSUE TITLE
Broken JitPack build since 66e5a9641c

### ISSUE THREAD

**Issue by DeflatedPickle** [mickleness/pumpernickel#75]
To start with, in case you're not aware, JitPack is a service that allows people to add a GitHub repository as a dependency with Maven or Gradle, by building artefacts and hosting them on their Maven.

The old Maven structure in 66e5a9641c worked with JitPack's build, however, since the release after that, it started to not [build artefacts](https://jitpack.io/com/github/mickleness/pumpernickel/-65c0a35f70-1/build.log).

This was fixed, however, it's now giving [this log](https://jitpack.io/com/github/mickleness/pumpernickel/530644ee10/build.log) with the latest commit.
> ShadowRenderer.java:[22,16] default methods are not supported in -source 1.7

**Comment by mickleness** [comment]
I'm not familiar with JitPack. (Does this mean someone else is using this project? I thought it was just me.)

I recently started adding some Java 1.8 features, and I neglected to update the pom.xml file. I just updated it with this commit:
https://github.com/mickleness/pumpernickel/commit/df041ea4b438f04917f5675fc1a11ebf519aa27f

How do I check to confirm if this resolved the issue on jitpack's end?

**Comment by DeflatedPickle** [comment]
I would like to use it if I can!

It can be checked on [the site](https://jitpack.io/#mickleness/pumpernickel/df041ea4b4), and then clicking the "`Get It`" button by the commit. But I don't know if that commit fixed it, it isn't processing that commit like the others.

I've never published to JitPack with Maven, but I have a few things on there I've published with Gradle. I could try converting your build scripts to Gradle and PR them? Or convert them and keep an updated fork.

**Comment by mickleness** [comment]
Hmm. Sorry, it looks like I made some sloppy mistakes that made the project Mac-dependent. I pushed some changes just now that should help, but they required bumping the version up again (now Java 1.9). I didn't see the error about the DoubleBoxShadowRenderer, though. I think I fixed the others; I wonder if that was just related to unpushed code.

**Comment by DeflatedPickle** [comment]
That's fine! I constantly make those kinds of mistakes and force-revert it away.

Yeah, the `DoubleBoxShadowRenderer` error isn't popping up anymore, along with the others. However, there is a missing module error.

```[ERROR] /home/jitpack/build/src/main/java/com/pump/io/ZipIterator.java:[19,13] package javax.activation is not visible
[ERROR]   (package javax.activation is declared in module java.activation, which is not in the module graph)
[ERROR] /home/jitpack/build/src/main/java/com/pump/io/ZipIterator.java:[20,13] package javax.activation is not visible
[ERROR]   (package javax.activation is declared in module java.activation, which is not in the module graph)
[ERROR] /home/jitpack/build/src/main/java/com/pump/io/ZipIterator.java:[21,13] package javax.activation is not visible
[ERROR]   (package javax.activation is declared in module java.activation, which is not in the module graph)
[ERROR] /home/jitpack/build/src/main/java/com/pump/io/ZipIterator.java:[45,16] recursive constructor invocation
```

**Comment by mickleness** [comment]
OK, I just removed that class from the pump repo (into a separate project where it's actually used).

**Comment by DeflatedPickle** [comment]
That fixed it, no more bugs after that. Thank you so much! There's a lot of nice widgets here, I can't wait to use them!
